### ISSUE TITLE
Social media icons are not displayed on github pages

### ISSUE THREAD

**Issue by mcheremnov** [piazzai/cvless#19]
Hi there, I really liked this theme, but while I was align it to my needs I find a bug that not all icons of social media are displayed on main page under my profile pic. Curious the fact that on localhost this behavior is absent.
<img width="912" alt="Screenshot 2024-12-30 at 23 21 15" src="https://github.com/user-attachments/assets/bb9ead78-4d75-4d74-ad58-a1c08f722deb" />
<img width="1120" alt="Screenshot 2024-12-30 at 23 25 31" src="https://github.com/user-attachments/assets/4230faff-dd3a-44b9-860f-bc8cd2c9c545" />

Any chance you could help me with that? Any ideas or suggestions would be appreciated! 
Happy New Year)

**Comment by piazzai** [comment]
Hi! I've taken a look at your website and I'm pretty sure the problem is in your `_config.yml` file (lines 20 to 25).

```yml
social:
  x: cheremnovmaksym
  instagram: maximazimov
  linkedin: maksym-cheremnov-682585171
  github: mcheremnov
```

Change this to:

```yml
profile:
  x: https://x.com/cheremnovmaksym
  instagram: https://www.instagram.com/maximazimov
  linkedin: https://www.linkedin.com/in/maksym-cheremnov-682585171
  github: https://github.com/mcheremnov
```

The reason why this happened is that today I released a new version of the theme where the `social` variable is replaced by a new variable called `profile`, and each profile is not just a username now but a full URL. When you load the theme gem, you load the latest version, so `profile` is expected, but it isn't found in your config and the icon isn't rendered.

You don't see this behavior in your local development environment because there you still have the old version of the gem, which expects `social`.
